[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_NO_WARNINGS = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*", "node_modules/@prisma/client/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs", "@prisma/client"]

[functions.generateHeroImage]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
  external_node_modules = ["@netlify/plugin-nextjs"]
  timeout = 30

[functions.generateHeroName]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
  external_node_modules = ["@netlify/plugin-nextjs"]
  timeout = 30

[[edge_functions]]
  function = "rate-limiter"
  path = "/api/*"

[[edge_functions]]
  function = "generateHeroImage"
  path = "/api/hero-image"

[[edge_functions]]
  function = "generateHeroName"
  path = "/api/hero-name"

# Block common attack patterns
[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/.env.*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/wp-admin/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/wp-login.php"
  to = "/404"
  status = 404

[[redirects]]
  from = "/admin.php"
  to = "/404"
  status = 404

[scheduled-functions]
  cleanup-old-heroes = "@daily"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
  webp = true
  avif = true

# Enhanced security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=self, microphone=(), geolocation=(), payment=()"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://cloud.leonardo.ai https://cdn.leonardo.ai; connect-src 'self' https://cloud.leonardo.ai https://accounts.zoho.eu https://mail.zoho.eu; font-src 'self'"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for _next/static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API headers with CORS restrictions
# ⚠️ UPDATE THIS: Replace "https://yourdomain.com" with your actual domain
# Or remove the Access-Control-Allow-Origin line entirely if you don't need CORS for external API access
[[headers]]
  for = "/api/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "https://yourdomain.com"
    "Access-Control-Allow-Headers" = "Content-Type, Authorization"
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
    "Content-Type" = "application/json"
    "X-Content-Type-Options" = "nosniff"
    "X-Frame-Options" = "DENY"
