[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_NO_WARNINGS = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*", "node_modules/@prisma/client/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs", "@prisma/client"]

[functions.generateHeroImage]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
  external_node_modules = ["@netlify/plugin-nextjs"]
  timeout = 30

[functions.generateHeroName]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
  external_node_modules = ["@netlify/plugin-nextjs"]
  timeout = 30

[[edge_functions]]
  function = "generateHeroImage"
  path = "/api/hero-image"

[[edge_functions]]
  function = "generateHeroName"
  path = "/api/hero-name"

[scheduled-functions]
  cleanup-old-heroes = "@daily"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
  webp = true
  avif = true

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for _next/static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API headers
[[headers]]
  for = "/api/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Headers" = "Content-Type"
    "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
    "Content-Type" = "application/json"
    "X-Content-Type-Options" = "nosniff"
