[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]

[functions.generateHeroImage]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
  external_node_modules = ["@netlify/plugin-nextjs"]
  timeout = 30

[functions.generateHeroName]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
  external_node_modules = ["@netlify/plugin-nextjs"]
  timeout = 30

[[edge_functions]]
  function = "generateHeroImage"
  path = "/api/hero-image"

[[edge_functions]]
  function = "generateHeroName"
  path = "/api/hero-name"

[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

[[headers]]
  for = "/api/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Headers" = "Content-Type"
    "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
